/** Pure adapter contract checks. These do not certify WebGL pixels or aesthetics. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const THREE=await import(new URL('../../cinematic-world-map/node_modules/three/build/three.module.js',import.meta.url));
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const legacy=read('web/flat_renderer.js');
assert.equal(crypto.createHash('sha256').update(legacy).digest('hex'),'144487d6824a10cedb4c002629620859817d0b0b89e4fdc65d805c6e29c8dde4','Frozen legacy renderer changed');
const source=read('web/flat_polish_renderer.js').replace(/^import .*;\s*$/gm,'').replace(/export /g,'');
const clamp=(v,min=0,max=1)=>Math.min(max,Math.max(min,v));
const {polishSurfaceShader,polishFlatLabels,SceneFlatPolishRenderer,FLAT_POLISH_POLICY}=new Function('THREE','SceneFlatRenderer','flatClamp','flatNumber','flatSmooth',`${source}\nreturn {polishSurfaceShader,polishFlatLabels,SceneFlatPolishRenderer,FLAT_POLISH_POLICY};`)(THREE,class{},clamp,(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,v=>{v=clamp(v);return v*v*(3-2*v);});
let assertions=1;
const shader=legacy.match(/const surfaceFragment=`([\s\S]*?)`;/)[1],polished=polishSurfaceShader(shader);
assert.ok(polished.includes('vec3 terrainTint'));assertions++;
assert.ok(polished.includes('source-vec3(.24)'));assertions++;
assert.ok(polished.includes('vec3(.0045,.021,.053)'));assertions++;
assert.throws(()=>polishSurfaceShader('missing material contract'),/CONTRACT_CHANGED/);assertions++;
assert.throws(()=>new SceneFlatPolishRenderer({},{}),/OPT_IN_V004/);assertions++;
assert.equal(FLAT_POLISH_POLICY.primaryAircraftPixels1080,88);assertions++;
const context={font:'',measureText(text){const font=Number(this.font.match(/([\d.]+)px/)[1]);return {width:[...text].length*font*.53};}};
const input=[{text:'SEOUL',font:48,x:155,y:260,width:140,height:60,opacity:.4,spacing:1.8,anchor:{x:150,y:300}},{text:'TOKYO',font:52,x:280,y:268,width:160,height:65,opacity:.95,spacing:1.8,anchor:{x:250,y:305}},{text:'INFORMATION',information:true,font:38,x:100,y:100,width:210,height:50,opacity:.9}];
const saved=JSON.stringify(input),labels=polishFlatLabels(input,1080,1920,context);
assert.equal(JSON.stringify(input),saved,'Input label geometry mutated');assertions++;
assert.equal(labels[0].font,54);assertions++;
assert.equal(labels[0].width,5*54*.53+4*1.8);assertions++;
assert.equal(labels[0].opacity,.4*1.04,'Fade envelope destroyed');assertions++;
assert.deepEqual(labels[2],input[2],'Information timing/style changed');assertions++;
for(const label of labels.slice(0,2)){assert.ok(label.x>=1080*.09&&label.x+label.width<=1080*.87);assert.ok(label.y>=1920*.13&&label.y+label.height<=1920*.8);assertions+=2;}
const camera=new THREE.OrthographicCamera(-19,19,33.8,-33.8,.01,100);camera.position.z=50;camera.lookAt(0,0,0);camera.updateMatrixWorld(true);
const makeItem=id=>{const model=new THREE.Group();model.add(new THREE.Mesh(new THREE.BoxGeometry(1,1,.1),new THREE.MeshBasicMaterial({transparent:true})));model.position.z=.16;return {spec:{id,type:'aircraft'},model,shadow:new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial()),ghosts:[]};};
const itemA=makeItem('stationary'),itemB=makeItem('departing'),poses=[{position:new THREE.Vector3(0,0,.03),alpha:1,mode:'stop'},{position:new THREE.Vector3(0,0,.03),alpha:1,mode:'move'}];
const anchorsBefore=poses.map(p=>p.position.toArray()),displayOffsets=new Map();
const mock={w:2160,h:3840,camera,displayOffsets,entities:{items:[itemA,itemB]},core:{cam:{current:{span:38}},project(point){const p=point.clone().project(camera);return {x:(p.x+1)*1080,y:(1-p.y)*1920};}}};
SceneFlatPolishRenderer.prototype.polishEntities.call(mock,0,{entities:poses});
assert.deepEqual(poses.map(p=>p.position.toArray()),anchorsBefore,'Verified ground anchors mutated');assertions++;
assert.ok(itemA.model.position.x!==itemB.model.position.x,'Common-origin aircraft not visually separated');assertions++;
assert.ok(displayOffsets.get('stationary').displayOffsetPixels.x>0);assertions++;
assert.ok(itemB.model.scale.x>1,'Departing aircraft minimum did not apply');assertions++;
assert.ok(itemA.model.children[0].material.opacity<1,'Stopped proxy did not yield visual priority');assertions++;
console.log(JSON.stringify({passed:true,assertions,scope:'Source preservation, guarded shader adaptation, measured mobile text boxes, opt-in only. No pixel review or rendered movie.'},null,2));
