import {createRequire} from 'node:module';
import {writeFile,mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),legacy=path.resolve(root,'../cinematic-world-map');
const require=createRequire(path.join(legacy,'package.json')),{chromium}=require('playwright');
const options={};for(let i=2;i<process.argv.length;i++){let a=process.argv[i],at=a.indexOf('=');if(at>=0)options[a.slice(2,at)]=a.slice(at+1);else options[a.slice(2)]=process.argv[i+1]&&!process.argv[i+1].startsWith('--')?process.argv[++i]:true;}
if(!options.url||!options.output)throw Error('Required --url and --output');const output=path.resolve(options.output);if(existsSync(output))throw Error('Refusing existing preflight '+output);await mkdir(path.dirname(output),{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-dev-shm-usage']});
try{const page=await browser.newPage({viewport:{width:1080,height:1920}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const url=new URL(options.url);url.searchParams.set('width',String(options.width||540));await page.goto(url.href,{timeout:120000});await page.waitForFunction(()=>window.ready||window.renderError,{timeout:120000});const failure=await page.evaluate(()=>window.renderError||null);if(failure)throw Error(failure);const initialAudit=await page.evaluate(()=>window.app.audit(0));const numeric=await page.evaluate(()=>window.app.numericPreflight(30));const times=options.stills?String(options.stills).split(',').map(Number):[];const stillAudits=[];for(const time of times){const dest=output.replace(/\.json$/i,'')+`_${time.toFixed(2).replace('.','_')}.png`;if(existsSync(dest))throw Error('Refusing existing still '+dest);const frame=await page.evaluate(t=>{window.renderFrame(t);return {audit:window.app.audit(t),png:window.app.canvas.toDataURL('image/png').split(',')[1]};},time);await writeFile(dest,Buffer.from(frame.png,'base64'),{flag:'wx'});stillAudits.push({time,file:dest,...frame.audit});}const passed=numeric.finite&&!numeric.routeWithinEarth&&!numeric.entityWithinEarth&&!numeric.cameraWithinEarth&&numeric.maxCameraAngleDegreesPerFrame<=2.5&&!errors.length&&initialAudit.webglError===0&&initialAudit.fontReady&&!initialAudit.missingTextures.length&&stillAudits.every(a=>a.webglError===0&&a.textClipped.length===0&&!a.entityClipped.length&&!a.missingTextures.length&&!a.routeInsideEarth&&!a.routeDiscontinuities.length);const result={passed,numeric,initialAudit,stillAudits,errors};await writeFile(output,JSON.stringify(result,null,2),{flag:'wx'});console.log(JSON.stringify({passed,maxCameraAngle:numeric.maxCameraAngleDegreesPerFrame,minRouteRadius:numeric.minRouteRadius,output}));if(!passed)process.exitCode=1;}finally{await browser.close();}
